sudo: required
services:
  - docker

before_install: 
  - docker build -t vktandrapati/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vktandrapati/react-test npm run test

after_success: 
  - docker build -t tandrapati/multi-client ./client
  - docker build -t tandrapati/multi-server ./server
  - docker build -t tandrapati/multi-nginx ./nginx
  - docker build -t tandrapati/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tandrapati/multi-client
  - docker push tandrapati/multi-server
  - docker push tandrapati/multi-nginx
  - docker push tandrapati/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-627016657995'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY